### ISSUE TITLE
Ordered lists in documentation are not styled properly

### ISSUE THREAD

**Issue by cstyles** [rubyapi/rubyapi#1249]
Compare the documentation for the `Coverage` module on ruby-doc.org:

https://ruby-doc.org/stdlib-3.1.2/libdoc/coverage/rdoc/Coverage.html#module-Coverage-label-Usage

And on rubyapi.org:

https://rubyapi.org/3.1/o/coverage#module-Coverage-label-Usage

A couple other examples:
https://rubyapi.org/3.1/o/pp#method-c-width_for
https://rubyapi.org/3.1/o/readline#method-c-readline

It looks like there's a global CSS style that's interfering:

```css
menu, ol, ul {
  list-style: none;
  margin: 0;
  padding: 0;
}
```

Disabling `list-style: none` fixes the bug but also messes with the styling of the table of contents. Is it possible to only set `list-style: none` outside of the documentation?

**Comment by JPCodaLot** [comment]
I think this change caused some unwanted side effects!

![Screenshot_20221024_093543](https://user-images.githubusercontent.com/78742629/197567048-0de7fda6-5835-4d66-b702-be494d97d734.png)

List item numbers are getting covered up by the sidebar's scrollbar because they have no margin.
Here is an example: https://rubyapi.org/3.1/o/optionparser. I am using Chrome on Windows 11 if that changes anything.

I am not familiar with Tailwind CSS and hence don't feel comfortable creating a pull request but I thought I should still let you know about it. Its not terrible, you can still use the website without any problem. However it doesn't look great.
